Milestone Bubble Sort Project
shubhsk88/bubble-sort-ruby pull request #3
Opened 2020-04-28 19:17 UTC by shubhsk88

This PR address the implementation of the Buble sort algorithm which was implemented using ruby

2020-04-28 21:28 UTC, mosesogwo requested changes
**HI @shubhsk88, @thedekerone:clap:. Good job:+1:. Let's address the following:**
- Your bubble_sort_by is not returning the correct result. See my comment on the method.
- You can move the bubble_sort_by method into bubble_sort.rb so we have a single file.
- See other comments on your project below.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-28 21:28 UTC, mosesogwo commented on README.md
> +This is a project of two algorithms about bubble sorting in ruby
Include a short description of the two algorithms (name and function).

2020-04-28 21:28 UTC, mosesogwo commented on bubble_sort.rb
> +      arr[j] = swap
You can easily achieve this swap with 
`arr[i], arr[j] = arr[j], arr[i]`

2020-04-28 21:28 UTC, mosesogwo commented on bubble_sort_by.rb
> +      arr[j] = swap
You can easily achieve this swap with 
`arr[i], arr[j] = arr[j], arr[i]`

2020-04-28 21:28 UTC, mosesogwo commented on bubble_sort_by.rb
> +      next unless yield arr[i], arr[j]
This is the point where you should check if the yield is positive, not in the example.
When the yield is positive, it means the left item is greater than the right, and so there should be a swap.

What your code currently does is to swap every time the yield is not false or nil, which will not give the correct output.

2020-04-29 04:55 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @shubhsk88  and @thedekerone  :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, your methods are working fine, please merge this branch and continue congratulations :tada: :tada: :tada: 

[OPTIONAL]

- [ ] I strongly recommend the use of `arr.size` instead of `arr.length` to keep the Ruby convention

PROJECT STATUS: APPROVED :green_apple:

2020-04-29 20:09 UTC, merged